"""
===================================
API v1 Schemas 模块初始化
===================================

职责：
1. 导出所有 Pydantic 模型
"""

from api.v1.schemas.alerts import (
    AlertDeleteResponse,
    AlertNotificationItem,
    AlertNotificationListResponse,
    AlertRuleCreateRequest,
    AlertRuleItem,
    AlertRuleListResponse,
    AlertRuleTestResponse,
    AlertRuleUpdateRequest,
    AlertTriggerItem,
    AlertTriggerListResponse,
)
from api.v1.schemas.intelligence import (
    IntelligenceCreateDefaultsResponse,
    IntelligenceFetchRequest,
    IntelligenceFetchResponse,
    IntelligenceFetchStatus,
    IntelligenceItemListResponse,
    IntelligenceItemResponse,
    IntelligenceSourceCreateRequest,
    IntelligenceSourceItem,
    IntelligenceSourceListResponse,
    IntelligenceSourceTestRequest,
    IntelligenceSourceTestResponse,
    IntelligenceSourceUpdateRequest,
)
from api.v1.schemas.analysis import (
    AnalysisResultResponse,
    AnalyzeRequest,
    BatchTaskAcceptedResponse,
    TaskAccepted,
    TaskStatus,
)
from api.v1.schemas.backtest import (
    BacktestResultItem,
    BacktestResultsResponse,
    BacktestRunRequest,
    BacktestRunResponse,
    PerformanceMetrics,
)
from api.v1.schemas.common import (
    ErrorResponse,
    HealthResponse,
    RootResponse,
    SuccessResponse,
)
from api.v1.schemas.history import (
    AnalysisReport,
    DeleteHistoryRequest,
    DeleteHistoryResponse,
    HistoryItem,
    HistoryListResponse,
    NewsIntelItem,
    NewsIntelResponse,
    ReportDetails,
    ReportMeta,
    ReportStrategy,
    ReportSummary,
)
from api.v1.schemas.portfolio import (
    PortfolioAccountCreateRequest,
    PortfolioAccountItem,
    PortfolioAccountListResponse,
    PortfolioAccountSnapshot,
    PortfolioAccountUpdateRequest,
    PortfolioCashLedgerCreateRequest,
    PortfolioCashLedgerListItem,
    PortfolioCashLedgerListResponse,
    PortfolioCorporateActionCreateRequest,
    PortfolioCorporateActionListItem,
    PortfolioCorporateActionListResponse,
    PortfolioEventCreatedResponse,
    PortfolioFxRefreshResponse,
    PortfolioImportBrokerItem,
    PortfolioImportBrokerListResponse,
    PortfolioImportCommitResponse,
    PortfolioImportParseResponse,
    PortfolioImportTradeItem,
    PortfolioPositionItem,
    PortfolioRiskResponse,
    PortfolioSnapshotResponse,
    PortfolioTradeCreateRequest,
    PortfolioTradeListItem,
    PortfolioTradeListResponse,
)
from api.v1.schemas.stocks import (
    KLineData,
    StockHistoryResponse,
    StockQuote,
)
from api.v1.schemas.system_config import (
    ConfigValidationIssue,
    ExportSystemConfigResponse,
    ImportSystemConfigRequest,
    LLMCapabilityCheck,
    LLMCapabilityCheckResult,
    SystemConfigCategorySchema,
    SystemConfigConflictResponse,
    SystemConfigFieldSchema,
    SystemConfigItem,
    SystemConfigResponse,
    SystemConfigSchemaResponse,
    SystemConfigUpdateItem,
    SystemConfigValidationErrorResponse,
    TestLLMChannelRequest,
    TestLLMChannelResponse,
    UpdateSystemConfigRequest,
    UpdateSystemConfigResponse,
    ValidateSystemConfigRequest,
    ValidateSystemConfigResponse,
)

__all__ = [
    # common
    "RootResponse",
    "HealthResponse",
    "ErrorResponse",
    "SuccessResponse",
    # analysis
    "AnalyzeRequest",
    "AnalysisResultResponse",
    "TaskAccepted",
    "BatchTaskAcceptedResponse",
    "TaskStatus",
    # history
    "HistoryItem",
    "HistoryListResponse",
    "DeleteHistoryRequest",
    "DeleteHistoryResponse",
    "NewsIntelItem",
    "NewsIntelResponse",
    "AnalysisReport",
    "ReportMeta",
    "ReportSummary",
    "ReportStrategy",
    "ReportDetails",
    # stocks
    "StockQuote",
    "StockHistoryResponse",
    "KLineData",
    # backtest
    "BacktestRunRequest",
    "BacktestRunResponse",
    "BacktestResultItem",
    "BacktestResultsResponse",
    "PerformanceMetrics",
    # system config
    "SystemConfigFieldSchema",
    "SystemConfigCategorySchema",
    "SystemConfigSchemaResponse",
    "SystemConfigItem",
    "SystemConfigResponse",
    "ExportSystemConfigResponse",
    "SystemConfigUpdateItem",
    "UpdateSystemConfigRequest",
    "UpdateSystemConfigResponse",
    "ValidateSystemConfigRequest",
    "ImportSystemConfigRequest",
    "ConfigValidationIssue",
    "ValidateSystemConfigResponse",
    "LLMCapabilityCheck",
    "LLMCapabilityCheckResult",
    "TestLLMChannelRequest",
    "TestLLMChannelResponse",
    "SystemConfigValidationErrorResponse",
    "SystemConfigConflictResponse",
    # portfolio
    "PortfolioAccountCreateRequest",
    "PortfolioAccountUpdateRequest",
    "PortfolioAccountItem",
    "PortfolioAccountListResponse",
    "PortfolioTradeCreateRequest",
    "PortfolioCashLedgerCreateRequest",
    "PortfolioCorporateActionCreateRequest",
    "PortfolioEventCreatedResponse",
    "PortfolioTradeListItem",
    "PortfolioTradeListResponse",
    "PortfolioCashLedgerListItem",
    "PortfolioCashLedgerListResponse",
    "PortfolioCorporateActionListItem",
    "PortfolioCorporateActionListResponse",
    "PortfolioPositionItem",
    "PortfolioAccountSnapshot",
    "PortfolioSnapshotResponse",
    "PortfolioImportTradeItem",
    "PortfolioImportParseResponse",
    "PortfolioImportCommitResponse",
    "PortfolioImportBrokerItem",
    "PortfolioImportBrokerListResponse",
    "PortfolioFxRefreshResponse",
    "PortfolioRiskResponse",
    # alerts
    "AlertDeleteResponse",
    "AlertNotificationItem",
    "AlertNotificationListResponse",
    "AlertRuleCreateRequest",
    "AlertRuleItem",
    "AlertRuleListResponse",
    "AlertRuleTestResponse",
    "AlertRuleUpdateRequest",
    "AlertTriggerItem",
    "AlertTriggerListResponse",
    # intelligence
    "IntelligenceSourceCreateRequest",
    "IntelligenceSourceUpdateRequest",
    "IntelligenceSourceItem",
    "IntelligenceSourceListResponse",
    "IntelligenceItemResponse",
    "IntelligenceItemListResponse",
    "IntelligenceFetchRequest",
    "IntelligenceFetchResponse",
    "IntelligenceFetchStatus",
    "IntelligenceSourceTestRequest",
    "IntelligenceSourceTestResponse",
    "IntelligenceCreateDefaultsResponse",
]
